### ISSUE TITLE
gogol-admin-reports-0.2.0 data is incomplete

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-hashes#11] opened 2017-02-14 12:32 UTC
There exists a file `gogol-admin-reports/0.2.0/gogol-admin-reports.cabal` but no matching JSON file.

**Comment by snoyberg** [comment] 2017-02-14 12:34
This is an upstream issue with Hackage itself, please file there.

**Comment by peti** [comment] 2017-02-14 12:37
I'm supposed to complain about a missing JSON file in `all-cabal-hashes` to the Hackage people? What good will that do?

**Comment by snoyberg** [comment] 2017-02-14 12:44
I won't deal with belligerence. If you want to ask why this is an upstream
issue, I can explain. But I don't need to waste my time with this tone.

**Comment by peti** [comment] 2017-02-14 12:50
I am sorry. I had not realized that you'd perceive my tone as offensive and I had no intention to come across that way. I apologize.

If you will, could you please explain to me why this is an upstream issue so that I can go ahead and try to get it fixed?

**Comment by snoyberg** [comment] 2017-02-14 13:02
Sure, no problem. The issue is:

* Hackage Security doesn't always generate JSON files: https://github.com/haskell/hackage-security/issues/183
* The file you're looking for specifically broke the entire mirror process over the weekend: https://github.com/hvr/hackage-mirror-tool/issues/2
* Because the connection to the Hackage server itself is insecure (HTTP), we cannot rely with downloads from it being untampered unless there is a Hackage Security signature
    * If you're wondering: Yes, https://hackage.haskell.org does work, but that's connecting to a CDN, which itself has an insecure connection to the Hackage server itself
    * The mirror tool we run connects directly to Hackage over its insecure connection
* Therefore, there's no way that we can reliably generate the .json files without risk of a MITM attack

In the past we generated the JSON files ourselves without relying on the upstream information, but that was before I was aware of the insecure connection between the CDN and Hackage. @lehins updated the mirroring tools recently to fix this.

I'm not getting traction upstream on this issue, so additional voices would be helpful. Filing against hackage-server probably makes sense.

**Comment by gbaz** [comment] 2017-02-16 08:44
> Because the connection to the Hackage server itself is insecure (HTTP), we cannot rely with downloads from it being untampered unless there is a Hackage Security signature

I checked our cdn settings, and in fact we do use a tls conduit between our cdn and the origin server. Image verifying settings below. It may be the case that we did not do so in the past but certainly we have had such a connection for quite some time.

![image](https://cloud.githubusercontent.com/assets/1125849/23013669/ad2817ba-f3f9-11e6-8b32-1e78dd987568.png)

**Comment by snoyberg** [comment] 2017-02-16 08:49
My information was from September

https://github.com/haskell/hackage-server/issues/540

**Comment by peti** [comment] 2017-02-16 09:03
Upstream ticket is https://github.com/haskell/hackage-server/issues/488, which appears to be dead in the water since April 15th 2016. This is not very encouraging.

**Comment by gbaz** [comment] 2017-02-16 09:05
Don't despair. The renewed attention has revived interest in tackling it.

**Comment by snoyberg** [comment] 2018-07-23 03:21
The problem has been fixed by upstream.

**Closed as completed by snoyberg** 2018-07-23 03:21 UTC
